---
title: '**Eficiência Orçamentária de Municípios Brasileiros**'
subtitle: '**Alcance dos Objetivos de Desenvolvimento Sustentável**'
author: '**Autores:** <br>[Moisés Vassallo](http://lattes.cnpq.br/8821972747380756) <br>[Rafael Miranda](http://lattes.cnpq.br/4478766390160865) <br>[Victor Valerio](http://lattes.cnpq.br/1989464933096922) <br>[André Medeiros](http://lattes.cnpq.br/4069096016693580) <br>[José Arnaldo Montevechi](http://lattes.cnpq.br/2169751971927037)'
date: '**Última Atualização:** <br>`r format(Sys.Date(), "%d-%m-%Y")`'
output:
  rmdformats::downcute:
    self_contained: true
    default_style: 'light'
    downcute_theme: 'default'
---


```{r message=FALSE, warning=FALSE, include=FALSE}
# PACOTES: -----------------------------------------------------------------
library(magrittr)
library(ggplot2)
library(gridExtra)
library(plotly)


# IMPORTAÇÃO: --------------------------------------------------------------
base <- readxl::read_xlsx(path = '../dados/20240926dea_final.xlsx',
                          sheet = 1) %>%
  janitor::clean_names() %>% 
  dplyr::mutate(id_municipio = as.numeric(id_municipio))


estados <- geobr::read_state(year = 2020, 
                             showProgress = FALSE)


municipios <- geobr::read_municipal_seat(year = 2010, 
                                         showProgress = FALSE)


# ARRUMAÇÃO: ---------------------------------------------------------------
mapa_total <- municipios %>% 
  dplyr::left_join(base, by = c('code_muni' = 'id_municipio')) %>% 
  tidyr::drop_na() %>% 
  dplyr::select(code_muni,
                name_muni,
                abbrev_state,
                name_region, 
                geom)


mapa_insumos <- municipios %>% 
  dplyr::left_join(base, by = c('code_muni' = 'id_municipio')) %>% 
  tidyr::drop_na() %>% 
  dplyr::select(code_muni,
                name_muni,
                abbrev_state,
                name_region,
                !dplyr::contains('ODS'),
                geom) 

```



# INTRODUÇÃO


Lorem ipsum!


# ANÁLISE ENVOLTÓRIA DE DADOS


$$ \min{} \theta_0 = \sum_{i = 1}^{r} v_i \ x_{i0}$$
$$Sujeito \ à:$$
$$ \sum_{j = 1}^{s} u_j \ y_{j0} = 1 $$
$$(\sum_{i = 1}^{r} v_i \ x_{ik}) - (\sum_{j = 1}^{s} u_j \ y_{jk}) = 0, \forall  \ k$$
$$v_i, \ u_j \geq 0, \forall \ i, \ j$$
$$$$

Lorem ipsum!

# RESULTADOS PRELIMINARES

```{r echo=FALSE, message=FALSE, warning=FALSE}
g1_amostra <- as.data.frame(mapa_total) %>% 
  dplyr::select(name_region) %>% 
  table() %>% 
  as.data.frame() %>% 
  dplyr::rename('regiao' = name_region,
                'municipios' = Freq) %>% 
  dplyr::mutate(regiao = as.character(regiao),
                municipios = as.numeric(municipios)) %>% 
  dplyr::arrange(desc(municipios)) %>% 
  dplyr::mutate(regiao = forcats::fct_reorder(regiao, municipios)) %>% 
  ggplot() + 
  geom_col(aes(x = municipios, y = regiao)) + 
  labs(x = 'Quantidade de Municípios',
       y = 'Região') + 
  theme_classic()

g1_amostra <- ggplotly(g1_amostra)

g2_amostra <- 
  ggplot() + 
  geom_sf(data = estados, 
          aes(),
          fill = 'white') + 
  geom_sf(data = mapa_total, 
          aes(),
          color = '#1F968BFF') +
  theme(axis.title=element_blank(),
        axis.text=element_blank(),
        axis.ticks=element_blank())

g2_amostra <- ggplotly(g2_amostra)

g2_amostra
```





Lorem ipsum!




































































